export const RECEIVE_LOCATION = 'RECEIVE_LOCATION';
export const SELECTED_STATION = 'SELECTED_STATION';
export const SELECTED_TRAIN = 'SELECTED_TRAIN';
export const SAVE_USER = 'SAVE_USER';

export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';
export const SOCKET_JOIN = 'SOCKET_JOIN';
export const DISPATCH_ROOM ='DISPATCH_ROOM';
export const DISPATCH_PARTICIPANTS = 'DISPATCH_PARTICIPANTS';
export const DISPATCH_READY_USERS = 'DISPATCH_READY_USERS';
export const DISPATCH_USER_STATUS = 'DISPATCH_USER_STATUS';
