export const RECEIVE_LOCATION = 'RECEIVE_LOCATION';
export const SELECTED_STATION = 'SELECTED_STATION';
export const SELECTED_TRAIN = 'SELECTED_TRAIN';
export const SAVE_USER = 'SAVE_USER';

export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';
export const SOCKET_JOIN = 'SOCKET_JOIN';
