// use in reducer

export const RECEIVE_LOCATION = 'RECEIVE_LOCATION';
export const SELECTED_STATION = 'SELECTED_STATION';
export const SELECTED_TRAIN = 'SELECTED_TRAIN';
export const SAVE_USER = 'SAVE_USER';

export const DISPATCH_ROOM ='DISPATCH_ROOM';
export const DISPATCH_USER_STATUS = 'DISPATCH_USER_STATUS';
export const DISPATCH_PARTICIPANTS = 'DISPATCH_PARTICIPANTS';

// use in middleware

export const SOCKET_JOIN = 'SOCKET_JOIN';
export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const DISPATCH_USER_TURN = 'DISPATCH_USER_TURN';
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';
export const DISPATCH_READY_USERS = 'DISPATCH_READY_USERS';
export const DISPATCH_USER_INITIAL_INFO = 'DISPATCH_USER_INITIAL_INFO';
export const DISPATCH_USER_INFO_ON_GAME = 'DISPATCH_USER_INFO_ON_GAME';

export const DISPATCH_MESSAGE = 'DISPATCH_MESSAGE';
export const DISPATCH_CHAT_LIST = 'DISPATCH_CHAT_LIST';
export const UPDATE_GAME_INFO = 'UPDATE_GAME_INFO';
export const UPDATE_GAME_STATUS = 'UPDATE_GAME_STATUS';
export const RECEIVE_GAME_STATUS = 'RECEIVE_GAME_STATUS';
export const DISPATCH_GAME_RESULT = 'DISPATCH_GAME_RESULT';